name: CEO SCHOOL
favicon: null
layout_spectrum: 0.8871237332932651
typography_spectrum: 0.9354220991954207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d2e8f0'
    - '#fecec4'
    - '#333233'
    - '#b1938d'
  brandStrength: 1
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.940220253309235
purpose: []
